src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\EquatableInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * Class User
 * @package App\Entity
 * @ORM\Entity
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({"employee" = "App\Entity\Employee", "contact" = "App\Entity\Contact"})
 */
abstract class User implements UserInterface, \Serializable, EquatableInterface
{
    /**
     * @var int|null
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected ?int $id = null;

    /**
     * @var string|null
     * @ORM\Column
     */
    protected ?string $firstName = null;

    /**
     * @var string|null
     * @ORM\Column
     */
    protected ?string $lastName = null;

    /**
     * @var string|null
     * @ORM\Column(unique=true)
     */
    protected ?string $email = null;

    /**
     * @var string|null
     * @ORM\Column
     */
    protected ?string $password = null;

    /**
     * @var string|null
     */
    protected ?string $plainPassword = null;

    /**
     * @var \DateTimeInterface
     * @ORM\Column(type="datetime_immutable")
     */
    protected \DateTimeInterface $registeredAt;

    /**
     * User constructor.
     */
    public function __construct()
    {
        $this->registeredAt = new \DateTimeImmutable();
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    /**
     * @param string|null $firstName
     */
    public function setFirstName(?string $firstName): self
    {
        $this->firstName = $firstName;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    /**
     * @param string|null $lastName
     */
    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getFullName(): ?string
    {
        return $this->firstName . " " . $this->lastName;
    }

    /**
     * @return string|null
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * @param string|null $email
     */
    public function setEmail(?string $email): self
    {
        $this->email = $email;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    /**
     * @param string|null $password
     */
    public function setPassword(?string $password): self
    {
        $this->password = $password;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    /**
     * @param string|null $plainPassword
     */
    public function setPlainPassword(?string $plainPassword): self
    {
        $this->plainPassword = $plainPassword;
        return $this;
    }

    /**
     * @return \DateTimeInterface
     */
    public function getRegisteredAt(): \DateTimeInterface
    {
        return $this->registeredAt;
    }

    /**
     * @inheritDoc
     */
    public function getSalt()
    {
    }

    /**
     * @inheritDoc
     */
    public function getUsername()
    {
        return $this->email;
    }

    /**
     * @inheritDoc
     */
    public function eraseCredentials()
    {
    }

    /**
     * @inheritDoc
     */
    public function serialize()
    {
        return serialize([$this->email]);
    }

    /**
     * @inheritDoc
     */
    public function unserialize($serialized)
    {
        list ($this->email) = unserialize($serialized, ['allowed_classes' => false]);
    }

    /**
     * @inheritDoc
     */
    public function isEqualTo(UserInterface $user)
    {
        return $user->getUsername() === $this->getUsername();
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="application-name" content="optigas"/>
        <meta name="author" content="abwopda@yahoo.com">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        {% block meta %}{% endblock %}
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

        <title>{% block title %}{{ app_config.app_name }}{% endblock %}</title>
        <link rel="shortcut icon" type="image/x-icon" href="{{ asset('images/icon.png') }}" />

        <style>{{ app_config.app_css }}</style>
    </head>
    {% block container %}
        {% block breadcrumb %} {% endblock %}
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    {% endblock container %}
</html>

templates/layout.html.twig
{% extends 'base.html.twig' %}
    {% block stylesheets %}
        {#{{ encore_entry_link_tags('app') }}#}

        <link href="{{ asset('css/bootstrap.css') }}" rel="stylesheet">
        <link href="{{ asset('css/layout.css') }}" rel="stylesheet">
        <link href="{{ asset('css/main.css') }}" rel="stylesheet">
        <link href="{{ asset('css/select2.css') }}" rel="stylesheet">
        <link href="{{ asset('css/bootstrap-treeview.css') }}" rel="stylesheet">
        <link href="{{ asset('css/tableexport.min.css') }}" rel="stylesheet">
    {% endblock %}
    {% block container %}
        <body class="theme1">
        {% include "ui/Default/menu.html.twig" %}

        <div class="visible-print col-md-12 text-left"><img src="{#{ asset( 'images/header.png' )}#}" alt="logo" /></div>
        <section class="wrap">
            <header id="adminbar">
                <div id="logo"><img src="{{ asset( app_config.app_logo )}}" alt="logo" class="img-small" /> <span>{{ app_config.app_name }}</span></div>
                <div class="dropdown pull-right user-profile">
                    <a href="#" id="drop3" role="button" class="dropdown-toggle" data-toggle="dropdown">
                        <img class="img-small" src="{#{ asset( app.user.image.getwebpath)}#}" alt="{{ app.user.username }}">
                        {{ app.user.fullName }} <span class="glyphicon glyphicon-chevron-down"></span></a>


                    <ul class="dropdown-menu">
                        <li>
                            <div class="navbar-content">
                                <div class="row">
                                    <div class="col-md-5">
                                        <img src="{#{ asset( app.user.image.getwebpath)}#}" alt="Alternate Text" class="img-responsive" />
                                        <div class="clearfix"></div>
                                        <p></p>
                                    </div>
                                    <div class="col-md-7">
                                        <span>{{ app.user.username }}</span>
                                        <p class="text-muted small">{{ app.user.email }}</p>
                                        <div class="divider"></div>
                                        <a href="{#{ path('profile_edit', { 'name': app.user.username}) }#}" class="btn btn-primary btn-sm">Afficher mon profil</a>
                                    </div>
                                </div>
                            </div>
                            <div class="navbar-footer">
                                <div class="navbar-footer-content">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <a href="{#{ path('fos_user_profile_edit') }#}" class="btn btn-default btn-sm">Compte</a>
                                        </div>
                                        <div class="col-md-6">
                                            <a href="{#{ path('fos_user_security_logout') }#}" class="btn btn-default btn-sm pull-right">Déconnexion</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </header>

            <div class="container">
                {% include "ui/Default/flashes.html.twig" %}
                {% block breadcrumb %} {% endblock %}
                {% block body %}{% endblock %}
            </div>
        </section>
        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}

            <script src="{{ asset('js/jquery.min.js') }}"></script>
            <script src="{{ asset('js/bootstrap.js') }}"></script>
            <script src="{{ asset('js/jquery.cookie.js') }}"></script>
            <script src="{{ asset('js/select2.min.js') }}"></script>
            <script src="{{ asset('js/xlsx.core.min.js') }}"></script>
            <script src="{{ asset('js/FileSaver.min.js') }}"></script>
            <script src="{{ asset('js/tableexport.min.js') }}"></script>
            <script src="{{ asset('js/app.js') }}"></script>
            <script src="{{ asset('bundles/fosjsrouting/js/router.min.js') }}"></script>
            <script src="{{ path('fos_js_routing_js', { callback: 'fos.Router.setData' }) }}"></script>
            <script>
                (function($) {
                    $('select').select2();
                    /*$('select').select2({
                        theme: "bootstrap"
                    });*/
                })(jQuery);
            </script>
        {% endblock %}
    </body>
    {% endblock container %}